export const languages = [
    { code: 'aa', label: 'Afar', default: false },
    { code: 'ab', label: 'Abkhazian', default: false },
    { code: 'af', label: 'Afrikaans', default: false },
    { code: 'sq', label: 'Albanian', default: false },
    { code: 'am', label: 'Amharic', default: false },
    { code: 'ar', label: 'Arabic', default: false },
    { code: 'an', label: 'Aragonese', default: false },
    { code: 'hy', label: 'Armenian', default: false },
    { code: 'as', label: 'Assamese', default: false },
    { code: 'av', label: 'Avaric', default: false },
    { code: 'ae', label: 'Avestan', default: false },
    { code: 'ay', label: 'Aymara', default: false },
    { code: 'az', label: 'Azerbaijani', default: false },
    { code: 'ba', label: 'Bashkir', default: false },
    { code: 'bm', label: 'Bambara', default: false },
    { code: 'eu', label: 'Basque', default: false },
    { code: 'be', label: 'Belarusian', default: false },
    { code: 'bn', label: 'Bengali', default: false },
    { code: 'bh', label: 'Bihari', default: false },
    { code: 'bi', label: 'Bislama', default: false },
    { code: 'bo', label: 'Tibetan', default: false },
    { code: 'bs', label: 'Bosnian', default: false },
    { code: 'br', label: 'Breton', default: false },
    { code: 'bg', label: 'Bulgarian', default: false },
    { code: 'my', label: 'Burmese', default: false },
    { code: 'ca', label: 'Catalan', default: false },
    { code: 'ca', label: 'Valencian', default: false },
    { code: 'cs', label: 'Czech', default: false },
    { code: 'ch', label: 'Chamorro', default: false },
    { code: 'ce', label: 'Chechen', default: false },
    { code: 'zh', label: 'Chinese', default: false },
    { code: 'cu', label: 'Church Slavic', default: false },
    { code: 'cu', label: 'Old Slavonic', default: false },
    { code: 'cu', label: 'Church Slavonic', default: false },
    { code: 'cu', label: 'Old Bulgarian;', default: false },
    { code: 'cu', label: 'Old Church Slavonic', default: false },
    { code: 'cv', label: 'Chuvash', default: false },
    { code: 'kw', label: 'Cornish', default: false },
    { code: 'co', label: 'Corsican', default: false },
    { code: 'cr', label: 'Cree', default: false },
    { code: 'cy', label: 'Welsh', default: false },
    { code: 'da', label: 'Danish', default: false },
    { code: 'de', label: 'German', default: false },
    { code: 'dv', label: 'Divehi', default: false },
    { code: 'dv', label: 'Dhivehi', default: false },
    { code: 'dv', label: 'Maldivian', default: false },
    { code: 'nl', label: 'Dutch; Flemish', default: false },
    { code: 'dz', label: 'Dzongkha', default: false },
    { code: 'en', label: 'English', default: true },
    { code: 'eo', label: 'Esperanto', default: false },
    { code: 'et', label: 'Estonian', default: false },
    { code: 'ee', label: 'Ewe', default: false },
    { code: 'fo', label: 'Faroese', default: false },
    { code: 'fa', label: 'Persian', default: false },
    { code: 'fj', label: 'Fijian', default: false },
    { code: 'fi', label: 'Finnish', default: false },
    { code: 'fr', label: 'French', default: false },
    { code: 'fy', label: 'Western Frisian', default: false },
    { code: 'ff', label: 'Fulah', default: false },
    { code: 'ka', label: 'Georgian', default: false },
    { code: 'gd', label: 'Gaelic', default: false },
    { code: 'gd', label: 'Scottish Gaelic', default: false },
    { code: 'ga', label: 'Irish', default: false },
    { code: 'gl', label: 'Galician', default: false },
    { code: 'gv', label: 'Manx', default: false },
    { code: 'el', label: 'Greek', default: false },
    { code: 'gn', label: 'Guarani', default: false },
    { code: 'gu', label: 'Gujarati', default: false },
    { code: 'ht', label: 'Haitian', default: false },
    { code: 'ht', label: 'Haitian Creole', default: false },
    { code: 'ha', label: 'Hausa', default: false },
    { code: 'he', label: 'Hebrew', default: false },
    { code: 'hz', label: 'Herero', default: false },
    { code: 'hi', label: 'Hindi', default: false },
    { code: 'ho', label: 'Hiri Motu', default: false },
    { code: 'hr', label: 'Croatian', default: false },
    { code: 'hu', label: 'Hungarian', default: false },
    { code: 'ig', label: 'Igbo', default: false },
    { code: 'is', label: 'Icelandic', default: false },
    { code: 'io', label: 'Ido', default: false },
    { code: 'ii', label: 'Sichuan Yi', default: false },
    { code: 'iu', label: 'Inuktitut', default: false },
    { code: 'ie', label: 'Interlingue', default: false },
    { code: 'ia', label: 'Interlingua', default: false },
    { code: 'id', label: 'Indonesian', default: false },
    { code: 'ik', label: 'Inupiaq', default: false },
    { code: 'it', label: 'Italian', default: false },
    { code: 'jv', label: 'Javanese', default: false },
    { code: 'ja', label: 'Japanese', default: false },
    { code: 'kl', label: 'Kalaallisut', default: false },
    { code: 'kl', label: 'Greenlandic', default: false },
    { code: 'kn', label: 'Kannada', default: false },
    { code: 'ks', label: 'Kashmiri', default: false },
    { code: 'kr', label: 'Kanuri', default: false },
    { code: 'kk', label: 'Kazakh', default: false },
    { code: 'km', label: 'Central Khmer', default: false },
    { code: 'ki', label: 'Kikuyu', default: false },
    { code: 'ki', label: 'Gikuyu', default: false },
    { code: 'rw', label: 'Kinyarwanda', default: false },
    { code: 'ky', label: 'Kirghiz', default: false },
    { code: 'ky', label: 'Kyrgyz', default: false },
    { code: 'kv', label: 'Komi', default: false },
    { code: 'kg', label: 'Kongo', default: false },
    { code: 'ko', label: 'Korean', default: false },
    { code: 'kj', label: 'Kuanyama', default: false },
    { code: 'kj', label: 'Kwanyama', default: false },
    { code: 'ku', label: 'Kurdish', default: false },
    { code: 'lo', label: 'Lao', default: false },
    { code: 'la', label: 'Latin', default: false },
    { code: 'lv', label: 'Latvian', default: false },
    { code: 'li', label: 'Limburgan', default: false },
    { code: 'li', label: 'Limburger', default: false },
    { code: 'li', label: 'Limburgish', default: false },
    { code: 'ln', label: 'Lingala', default: false },
    { code: 'lt', label: 'Lithuanian', default: false },
    { code: 'lb', label: 'Luxembourgish', default: false },
    { code: 'lb', label: 'Letzeburgesch', default: false },
    { code: 'lu', label: 'Luba-Katanga', default: false },
    { code: 'lg', label: 'Ganda', default: false },
    { code: 'mk', label: 'Macedonian', default: false },
    { code: 'mh', label: 'Marshallese', default: false },
    { code: 'ml', label: 'Malayalam', default: false },
    { code: 'mi', label: 'Maori', default: false },
    { code: 'mr', label: 'Marathi', default: false },
    { code: 'ms', label: 'Malay', default: false },
    { code: 'mg', label: 'Malagasy', default: false },
    { code: 'mt', label: 'Maltese', default: false },
    { code: 'mo', label: 'Moldavian', default: false },
    { code: 'mn', label: 'Mongolian', default: false },
    { code: 'na', label: 'Nauru', default: false },
    { code: 'nv', label: 'Navajo', default: false },
    { code: 'nv', label: 'Navaho', default: false },
    { code: 'nr', label: 'Ndebele South', default: false },
    { code: 'nr', label: 'South Ndebele', default: false },
    { code: 'nr', label: 'Ndebele North', default: false },
    { code: 'nd', label: 'North Ndebele', default: false },
    { code: 'ng', label: 'Ndonga', default: false },
    { code: 'ne', label: 'Nepali', default: false },
    { code: 'nl', label: 'Dutch', default: false },
    { code: 'nn', label: 'Norwegian Nynorsk', default: false },
    { code: 'nn', label: 'Nynorsk Norwegian', default: false },
    { code: 'nb', label: 'Bokmål Norwegian', default: false },
    { code: 'nb', label: 'Norwegian Bokmål', default: false },
    { code: 'no', label: 'Norwegian', default: false },
    { code: 'ny', label: 'Chichewa', default: false },
    { code: 'ny', label: 'Nyanja', default: false },
    { code: 'oc', label: 'Occitan ', default: false },
    { code: 'oc', label: 'Provençal', default: false },
    { code: 'oj', label: 'Ojibwa', default: false },
    { code: 'or', label: 'Oriya', default: false },
    { code: 'om', label: 'Oromo', default: false },
    { code: 'os', label: 'Ossetian', default: false },
    { code: 'os', label: 'Ossetic', default: false },
    { code: 'pa', label: 'Panjabi', default: false },
    { code: 'pa', label: 'Punjabi', default: false },
    { code: 'pi', label: 'Pali', default: false },
    { code: 'pl', label: 'Polish', default: false },
    { code: 'pt', label: 'Portuguese', default: false },
    { code: 'ps', label: 'Pushto', default: false },
    { code: 'qu', label: 'Quechua', default: false },
    { code: 'rm', label: 'Romansh', default: false },
    { code: 'ro', label: 'Romanian', default: false },
    { code: 'rn', label: 'Rundi', default: false },
    { code: 'ru', label: 'Russian', default: false },
    { code: 'sg', label: 'Sango', default: false },
    { code: 'sa', label: 'Sanskrit', default: false },
    { code: 'sr', label: 'Serbian', default: false },
    { code: 'si', label: 'Sinhala', default: false },
    { code: 'si', label: 'Sinhalese', default: false },
    { code: 'sk', label: 'Slovak', default: false },
    { code: 'sl', label: 'Slovenian', default: false },
    { code: 'se', label: 'Northern Sami', default: false },
    { code: 'sm', label: 'Samoan', default: false },
    { code: 'sn', label: 'Shona', default: false },
    { code: 'sd', label: 'Sindhi', default: false },
    { code: 'so', label: 'Somali', default: false },
    { code: 'st', label: 'Sotho Southern', default: false },
    { code: 'es', label: 'Spanish', default: false },
    { code: 'es', label: 'Castilian', default: false },
    { code: 'sc', label: 'Sardinian', default: false },
    { code: 'ss', label: 'Swati', default: false },
    { code: 'su', label: 'Sundanese', default: false },
    { code: 'sw', label: 'Swahili', default: false },
    { code: 'sv', label: 'Swedish', default: false },
    { code: 'ty', label: 'Tahitian', default: false },
    { code: 'ta', label: 'Tamil', default: false },
    { code: 'tt', label: 'Tatar', default: false },
    { code: 'te', label: 'Telugu', default: false },
    { code: 'tg', label: 'Tajik', default: false },
    { code: 'tl', label: 'Tagalog', default: false },
    { code: 'th', label: 'Thai', default: false },
    { code: 'ti', label: 'Tigrinya', default: false },
    { code: 'to', label: 'Tonga ', default: false },
    { code: 'to', label: 'Tonga Islands', default: false },
    { code: 'tn', label: 'Tswana', default: false },
    { code: 'ts', label: 'Tsonga', default: false },
    { code: 'tk', label: 'Turkmen', default: false },
    { code: 'tr', label: 'Turkish', default: false },
    { code: 'tw', label: 'Twi', default: false },
    { code: 'ug', label: 'Uighur', default: false },
    { code: 'ug', label: 'Uyghur', default: false },
    { code: 'uk', label: 'Ukrainian', default: false },
    { code: 'ur', label: 'Urdu', default: false },
    { code: 'uz', label: 'Uzbek', default: false },
    { code: 've', label: 'Venda', default: false },
    { code: 'vi', label: 'Vietnamese', default: false },
    { code: 'vo', label: 'Volapük', default: false },
    { code: 'wa', label: 'Walloon', default: false },
    { code: 'wo', label: 'Wolof', default: false },
    { code: 'xh', label: 'Xhosa', default: false },
    { code: 'yi', label: 'Yiddish', default: false },
    { code: 'yo', label: 'Yoruba', default: false },
    { code: 'za', label: 'Zhuang Chuang', default: false },
    { code: 'zu', label: 'Zulu', default: false },
    { code: 'AsT', label: 'Asante Twi', default: false },
    { code: 'AkT', label: 'Akuapem Twi', default: false },
    { code: 'Ew', label: 'Ewe', default: false },
    { code: 'Ga', label: 'Ga', default: false },
    { code: 'Mfts', label: 'Mfantse', default: false }
];

export const nationalities = [
    { code: 'AF', label: 'Afghanistan', default: false },
    { code: 'AX', label: 'Åland Islands', default: false },
    { code: 'AL', label: 'Albania', default: false },
    { code: 'DZ', label: 'Algeria', default: false },
    { code: 'AS', label: 'American Samoa', default: false },
    { code: 'AD', label: 'Andorra', default: false },
    { code: 'AO', label: 'Angola', default: false },
    { code: 'AI', label: 'Anguilla', default: false },
    { code: 'AQ', label: 'Antarctica', default: false },
    { code: 'AG', label: 'Antigua and Barbuda', default: false },
    { code: 'AR', label: 'Argentina', default: false },
    { code: 'AM', label: 'Armenia', default: false },
    { code: 'AW', label: 'Aruba', default: false },
    { code: 'AU', label: 'Australia', default: false },
    { code: 'AT', label: 'Austria', default: false },
    { code: 'AZ', label: 'Azerbaijan', default: false },
    { code: 'BS', label: 'Bahamas', default: false },
    { code: 'BH', label: 'Bahrain', default: false },
    { code: 'BD', label: 'Bangladesh', default: false },
    { code: 'BB', label: 'Barbados', default: false },
    { code: 'BY', label: 'Belarus', default: false },
    { code: 'BE', label: 'Belgium', default: false },
    { code: 'BZ', label: 'Belize', default: false },
    { code: 'BJ', label: 'Benin', default: false },
    { code: 'BM', label: 'Bermuda', default: false },
    { code: 'BT', label: 'Bhutan', default: false },
    { code: 'BO', label: 'Bolivia, Plurinational State of', default: false },
    { code: 'BQ', label: 'Bonaire, Sint Eustatius and Saba', default: false },
    { code: 'BA', label: 'Bosnia and Herzegovina', default: false },
    { code: 'BW', label: 'Botswana', default: false },
    { code: 'BV', label: 'Bouvet Island', default: false },
    { code: 'BR', label: 'Brazil', default: false },
    { code: 'IO', label: 'British Indian Ocean Territory', default: false },
    { code: 'BN', label: 'Brunei Darussalam', default: false },
    { code: 'BG', label: 'Bulgaria', default: false },
    { code: 'BF', label: 'Burkina Faso', default: false },
    { code: 'BI', label: 'Burundi', default: false },
    { code: 'KH', label: 'Cambodia', default: false },
    { code: 'CM', label: 'Cameroon', default: false },
    { code: 'CA', label: 'Canada', default: false },
    { code: 'CV', label: 'Cape Verde', default: false },
    { code: 'KY', label: 'Cayman Islands', default: false },
    { code: 'CF', label: 'Central African Republic', default: false },
    { code: 'TD', label: 'Chad', default: false },
    { code: 'CL', label: 'Chile', default: false },
    { code: 'CN', label: 'China', default: false },
    { code: 'CX', label: 'Christmas Island', default: false },
    { code: 'CC', label: 'Cocos (Keeling) Islands', default: false },
    { code: 'CO', label: 'Colombia', default: false },
    { code: 'KM', label: 'Comoros', default: false },
    { code: 'CG', label: 'Congo', default: false },
    { code: 'CD', label: 'Congo, the Democratic Republic of the', default: false },
    { code: 'CK', label: 'Cook Islands', default: false },
    { code: 'CR', label: 'Costa Rica', default: false },
    { code: 'CI', label: 'Côte d\'Ivoire', default: false },
    { code: 'HR', label: 'Croatia', default: false },
    { code: 'CU', label: 'Cuba', default: false },
    { code: 'CW', label: 'Curaçao', default: false },
    { code: 'CY', label: 'Cyprus', default: false },
    { code: 'CZ', label: 'Czech Republic', default: false },
    { code: 'DK', label: 'Denmark', default: false },
    { code: 'DJ', label: 'Djibouti', default: false },
    { code: 'DM', label: 'Dominica', default: false },
    { code: 'DO', label: 'Dominican Republic', default: false },
    { code: 'EC', label: 'Ecuador', default: false },
    { code: 'EG', label: 'Egypt', default: false },
    { code: 'SV', label: 'El Salvador', default: false },
    { code: 'GQ', label: 'Equatorial Guinea', default: false },
    { code: 'ER', label: 'Eritrea', default: false },
    { code: 'EE', label: 'Estonia', default: false },
    { code: 'ET', label: 'Ethiopia', default: false },
    { code: 'FK', label: 'Falkland Islands (Malvinas)', default: false },
    { code: 'FO', label: 'Faroe Islands', default: false },
    { code: 'FJ', label: 'Fiji', default: false },
    { code: 'FI', label: 'Finland', default: false },
    { code: 'FR', label: 'France', default: false },
    { code: 'GF', label: 'French Guiana', default: false },
    { code: 'PF', label: 'French Polynesia', default: false },
    { code: 'TF', label: 'French Southern Territories', default: false },
    { code: 'GA', label: 'Gabon', default: false },
    { code: 'GM', label: 'Gambia', default: false },
    { code: 'GE', label: 'Georgia', default: false },
    { code: 'DE', label: 'Germany', default: false },
    { code: 'GH', label: 'Ghana', default: true },
    { code: 'GI', label: 'Gibraltar', default: false },
    { code: 'GR', label: 'Greece', default: false },
    { code: 'GL', label: 'Greenland', default: false },
    { code: 'GD', label: 'Grenada', default: false },
    { code: 'GP', label: 'Guadeloupe', default: false },
    { code: 'GU', label: 'Guam', default: false },
    { code: 'GT', label: 'Guatemala', default: false },
    { code: 'GG', label: 'Guernsey', default: false },
    { code: 'GN', label: 'Guinea', default: false },
    { code: 'GW', label: 'Guinea-Bissau', default: false },
    { code: 'GY', label: 'Guyana', default: false },
    { code: 'HT', label: 'Haiti', default: false },
    { code: 'HM', label: 'Heard Island and McDonald Islands', default: false },
    { code: 'VA', label: 'Holy See (Vatican City State)', default: false },
    { code: 'HN', label: 'Honduras', default: false },
    { code: 'HK', label: 'Hong Kong', default: false },
    { code: 'HU', label: 'Hungary', default: false },
    { code: 'IS', label: 'Iceland', default: false },
    { code: 'IN', label: 'India', default: false },
    { code: 'ID', label: 'Indonesia', default: false },
    { code: 'IR', label: 'Iran, Islamic Republic of', default: false },
    { code: 'IQ', label: 'Iraq', default: false },
    { code: 'IE', label: 'Ireland', default: false },
    { code: 'IM', label: 'Isle of Man', default: false },
    { code: 'IL', label: 'Israel', default: false },
    { code: 'IT', label: 'Italy', default: false },
    { code: 'JM', label: 'Jamaica', default: false },
    { code: 'JP', label: 'Japan', default: false },
    { code: 'JE', label: 'Jersey', default: false },
    { code: 'JO', label: 'Jordan', default: false },
    { code: 'KZ', label: 'Kazakhstan', default: false },
    { code: 'KE', label: 'Kenya', default: false },
    { code: 'KI', label: 'Kiribati', default: false },
    { code: 'KP', label: 'Korea, Democratic People\'s Republic of', default: false },
    { code: 'KR', label: 'Korea, Republic of', default: false },
    { code: 'KW', label: 'Kuwait', default: false },
    { code: 'KG', label: 'Kyrgyzstan', default: false },
    { code: 'LA', label: 'Lao People\'s Democratic Republic', default: false },
    { code: 'LV', label: 'Latvia', default: false },
    { code: 'LB', label: 'Lebanon', default: false },
    { code: 'LS', label: 'Lesotho', default: false },
    { code: 'LR', label: 'Liberia', default: false },
    { code: 'LY', label: 'Libya', default: false },
    { code: 'LI', label: 'Liechtenstein', default: false },
    { code: 'LT', label: 'Lithuania', default: false },
    { code: 'LU', label: 'Luxembourg', default: false },
    { code: 'MO', label: 'Macao', default: false },
    { code: 'MK', label: 'Macedonia, the former Yugoslav Republic of', default: false },
    { code: 'MG', label: 'Madagascar', default: false },
    { code: 'MW', label: 'Malawi', default: false },
    { code: 'MY', label: 'Malaysia', default: false },
    { code: 'MV', label: 'Maldives', default: false },
    { code: 'ML', label: 'Mali', default: false },
    { code: 'MT', label: 'Malta', default: false },
    { code: 'MH', label: 'Marshall Islands', default: false },
    { code: 'MQ', label: 'Martinique', default: false },
    { code: 'MR', label: 'Mauritania', default: false },
    { code: 'MU', label: 'Mauritius', default: false },
    { code: 'YT', label: 'Mayotte', default: false },
    { code: 'MX', label: 'Mexico', default: false },
    { code: 'FM', label: 'Micronesia, Federated States of', default: false },
    { code: 'MD', label: 'Moldova, Republic of', default: false },
    { code: 'MC', label: 'Monaco', default: false },
    { code: 'MN', label: 'Mongolia', default: false },
    { code: 'ME', label: 'Montenegro', default: false },
    { code: 'MS', label: 'Montserrat', default: false },
    { code: 'MA', label: 'Morocco', default: false },
    { code: 'MZ', label: 'Mozambique', default: false },
    { code: 'MM', label: 'Myanmar', default: false },
    { code: 'NA', label: 'Namibia', default: false },
    { code: 'NR', label: 'Nauru', default: false },
    { code: 'NP', label: 'Nepal', default: false },
    { code: 'NL', label: 'Netherlands', default: false },
    { code: 'NC', label: 'New Caledonia', default: false },
    { code: 'NZ', label: 'New Zealand', default: false },
    { code: 'NI', label: 'Nicaragua', default: false },
    { code: 'NE', label: 'Niger', default: false },
    { code: 'NG', label: 'Nigeria', default: false },
    { code: 'NU', label: 'Niue', default: false },
    { code: 'NF', label: 'Norfolk Island', default: false },
    { code: 'MP', label: 'Northern Mariana Islands', default: false },
    { code: 'NO', label: 'Norway', default: false },
    { code: 'OM', label: 'Oman', default: false },
    { code: 'PK', label: 'Pakistan', default: false },
    { code: 'PW', label: 'Palau', default: false },
    { code: 'PS', label: 'Palestinian Territory, Occupied', default: false },
    { code: 'PA', label: 'Panama', default: false },
    { code: 'PG', label: 'Papua New Guinea', default: false },
    { code: 'PY', label: 'Paraguay', default: false },
    { code: 'PE', label: 'Peru', default: false },
    { code: 'PH', label: 'Philippines', default: false },
    { code: 'PN', label: 'Pitcairn', default: false },
    { code: 'PL', label: 'Poland', default: false },
    { code: 'PT', label: 'Portugal', default: false },
    { code: 'PR', label: 'Puerto Rico', default: false },
    { code: 'QA', label: 'Qatar', default: false },
    { code: 'RE', label: 'Réunion', default: false },
    { code: 'RO', label: 'Romania', default: false },
    { code: 'RU', label: 'Russian Federation', default: false },
    { code: 'RW', label: 'Rwanda', default: false },
    { code: 'BL', label: 'Saint Barthélemy', default: false },
    { code: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha', default: false },
    { code: 'KN', label: 'Saint Kitts and Nevis', default: false },
    { code: 'LC', label: 'Saint Lucia', default: false },
    { code: 'MF', label: 'Saint Martin (French part)', default: false },
    { code: 'PM', label: 'Saint Pierre and Miquelon', default: false },
    { code: 'VC', label: 'Saint Vincent and the Grenadines', default: false },
    { code: 'WS', label: 'Samoa', default: false },
    { code: 'SM', label: 'San Marino', default: false },
    { code: 'ST', label: 'Sao Tome and Principe', default: false },
    { code: 'SA', label: 'Saudi Arabia', default: false },
    { code: 'SN', label: 'Senegal', default: false },
    { code: 'RS', label: 'Serbia', default: false },
    { code: 'SC', label: 'Seychelles', default: false },
    { code: 'SL', label: 'Sierra Leone', default: false },
    { code: 'SG', label: 'Singapore', default: false },
    { code: 'SX', label: 'Sint Maarten (Dutch part)', default: false },
    { code: 'SK', label: 'Slovakia', default: false },
    { code: 'SI', label: 'Slovenia', default: false },
    { code: 'SB', label: 'Solomon Islands', default: false },
    { code: 'SO', label: 'Somalia', default: false },
    { code: 'ZA', label: 'South Africa', default: false },
    { code: 'GS', label: 'South Georgia and the South Sandwich Islands', default: false },
    { code: 'SS', label: 'South Sudan', default: false },
    { code: 'ES', label: 'Spain', default: false },
    { code: 'LK', label: 'Sri Lanka', default: false },
    { code: 'SD', label: 'Sudan', default: false },
    { code: 'SR', label: 'Suriname', default: false },
    { code: 'SJ', label: 'Svalbard and Jan Mayen', default: false },
    { code: 'SZ', label: 'Swaziland', default: false },
    { code: 'SE', label: 'Sweden', default: false },
    { code: 'CH', label: 'Switzerland', default: false },
    { code: 'SY', label: 'Syrian Arab Republic', default: false },
    { code: 'TW', label: 'Taiwan, Province of China', default: false },
    { code: 'TJ', label: 'Tajikistan', default: false },
    { code: 'TZ', label: 'Tanzania, United Republic of', default: false },
    { code: 'TH', label: 'Thailand', default: false },
    { code: 'TL', label: 'Timor-Leste', default: false },
    { code: 'TG', label: 'Togo', default: false },
    { code: 'TK', label: 'Tokelau', default: false },
    { code: 'TO', label: 'Tonga', default: false },
    { code: 'TT', label: 'Trinidad and Tobago', default: false },
    { code: 'TN', label: 'Tunisia', default: false },
    { code: 'TR', label: 'Turkey', default: false },
    { code: 'TM', label: 'Turkmenistan', default: false },
    { code: 'TC', label: 'Turks and Caicos Islands', default: false },
    { code: 'TV', label: 'Tuvalu', default: false },
    { code: 'UG', label: 'Uganda', default: false },
    { code: 'UA', label: 'Ukraine', default: false },
    { code: 'AE', label: 'United Arab Emirates', default: false },
    { code: 'GB', label: 'United Kingdom', default: false },
    { code: 'US', label: 'United States', default: false },
    { code: 'UM', label: 'United States Minor Outlying Islands', default: false },
    { code: 'UY', label: 'Uruguay', default: false },
    { code: 'UZ', label: 'Uzbekistan', default: false },
    { code: 'VU', label: 'Vanuatu', default: false },
    { code: 'VE', label: 'Venezuela, Bolivarian Republic of', default: false },
    { code: 'VN', label: 'Viet Nam', default: false },
    { code: 'VG', label: 'Virgin Islands, British', default: false },
    { code: 'VI', label: 'Virgin Islands, U.S.', default: false },
    { code: 'WF', label: 'Wallis and Futuna', default: false },
    { code: 'EH', label: 'Western Sahara', default: false },
    { code: 'YE', label: 'Yemen', default: false },
    { code: 'ZM', label: 'Zambia', default: false },
    { code: 'ZW', label: 'Zimbabwe', default: false }
];
