export const languages = [
    { code: 'aa', label: 'Afar', default: false },
    { code: 'ab', label: 'Abkhazian', default: false },
    { code: 'af', label: 'Afrikaans', default: false },
    { code: 'sq', label: 'Albanian', default: false },
    { code: 'am', label: 'Amharic', default: false },
    { code: 'ar', label: 'Arabic', default: false },
    { code: 'an', label: 'Aragonese', default: false },
    { code: 'hy', label: 'Armenian', default: false },
    { code: 'as', label: 'Assamese', default: false },
    { code: 'av', label: 'Avaric', default: false },
    { code: 'ae', label: 'Avestan', default: false },
    { code: 'ay', label: 'Aymara', default: false },
    { code: 'az', label: 'Azerbaijani', default: false },
    { code: 'ba', label: 'Bashkir', default: false },
    { code: 'bm', label: 'Bambara', default: false },
    { code: 'eu', label: 'Basque', default: false },
    { code: 'be', label: 'Belarusian', default: false },
    { code: 'bn', label: 'Bengali', default: false },
    { code: 'bh', label: 'Bihari', default: false },
    { code: 'bi', label: 'Bislama', default: false },
    { code: 'bo', label: 'Tibetan', default: false },
    { code: 'bs', label: 'Bosnian', default: false },
    { code: 'br', label: 'Breton', default: false },
    { code: 'bg', label: 'Bulgarian', default: false },
    { code: 'my', label: 'Burmese', default: false },
    { code: 'ca', label: 'Catalan', default: false },
    { code: 'ca', label: 'Valencian', default: false },
    { code: 'cs', label: 'Czech', default: false },
    { code: 'ch', label: 'Chamorro', default: false },
    { code: 'ce', label: 'Chechen', default: false },
    { code: 'zh', label: 'Chinese', default: false },
    { code: 'cu', label: 'Church Slavic', default: false },
    { code: 'cu', label: 'Old Slavonic', default: false },
    { code: 'cu', label: 'Church Slavonic', default: false },
    { code: 'cu', label: 'Old Bulgarian;', default: false },
    { code: 'cu', label: 'Old Church Slavonic', default: false },
    { code: 'cv', label: 'Chuvash', default: false },
    { code: 'kw', label: 'Cornish', default: false },
    { code: 'co', label: 'Corsican', default: false },
    { code: 'cr', label: 'Cree', default: false },
    { code: 'cy', label: 'Welsh', default: false },
    { code: 'da', label: 'Danish', default: false },
    { code: 'de', label: 'German', default: false },
    { code: 'dv', label: 'Divehi', default: false },
    { code: 'dv', label: 'Dhivehi', default: false },
    { code: 'dv', label: 'Maldivian', default: false },
    { code: 'nl', label: 'Dutch; Flemish', default: false },
    { code: 'dz', label: 'Dzongkha', default: false },
    { code: 'en', label: 'English', default: true },
    { code: 'eo', label: 'Esperanto', default: false },
    { code: 'et', label: 'Estonian', default: false },
    { code: 'ee', label: 'Ewe', default: false },
    { code: 'fo', label: 'Faroese', default: false },
    { code: 'fa', label: 'Persian', default: false },
    { code: 'fj', label: 'Fijian', default: false },
    { code: 'fi', label: 'Finnish', default: false },
    { code: 'fr', label: 'French', default: false },
    { code: 'fy', label: 'Western Frisian', default: false },
    { code: 'ff', label: 'Fulah', default: false },
    { code: 'ka', label: 'Georgian', default: false },
    { code: 'gd', label: 'Gaelic', default: false },
    { code: 'gd', label: 'Scottish Gaelic', default: false },
    { code: 'ga', label: 'Irish', default: false },
    { code: 'gl', label: 'Galician', default: false },
    { code: 'gv', label: 'Manx', default: false },
    { code: 'el', label: 'Greek', default: false },
    { code: 'gn', label: 'Guarani', default: false },
    { code: 'gu', label: 'Gujarati', default: false },
    { code: 'ht', label: 'Haitian', default: false },
    { code: 'ht', label: 'Haitian Creole', default: false },
    { code: 'ha', label: 'Hausa', default: false },
    { code: 'he', label: 'Hebrew', default: false },
    { code: 'hz', label: 'Herero', default: false },
    { code: 'hi', label: 'Hindi', default: false },
    { code: 'ho', label: 'Hiri Motu', default: false },
    { code: 'hr', label: 'Croatian', default: false },
    { code: 'hu', label: 'Hungarian', default: false },
    { code: 'ig', label: 'Igbo', default: false },
    { code: 'is', label: 'Icelandic', default: false },
    { code: 'io', label: 'Ido', default: false },
    { code: 'ii', label: 'Sichuan Yi', default: false },
    { code: 'iu', label: 'Inuktitut', default: false },
    { code: 'ie', label: 'Interlingue', default: false },
    { code: 'ia', label: 'Interlingua', default: false },
    { code: 'id', label: 'Indonesian', default: false },
    { code: 'ik', label: 'Inupiaq', default: false },
    { code: 'it', label: 'Italian', default: false },
    { code: 'jv', label: 'Javanese', default: false },
    { code: 'ja', label: 'Japanese', default: false },
    { code: 'kl', label: 'Kalaallisut', default: false },
    { code: 'kl', label: 'Greenlandic', default: false },
    { code: 'kn', label: 'Kannada', default: false },
    { code: 'ks', label: 'Kashmiri', default: false },
    { code: 'kr', label: 'Kanuri', default: false },
    { code: 'kk', label: 'Kazakh', default: false },
    { code: 'km', label: 'Central Khmer', default: false },
    { code: 'ki', label: 'Kikuyu', default: false },
    { code: 'ki', label: 'Gikuyu', default: false },
    { code: 'rw', label: 'Kinyarwanda', default: false },
    { code: 'ky', label: 'Kirghiz', default: false },
    { code: 'ky', label: 'Kyrgyz', default: false },
    { code: 'kv', label: 'Komi', default: false },
    { code: 'kg', label: 'Kongo', default: false },
    { code: 'ko', label: 'Korean', default: false },
    { code: 'kj', label: 'Kuanyama', default: false },
    { code: 'kj', label: 'Kwanyama', default: false },
    { code: 'ku', label: 'Kurdish', default: false },
    { code: 'lo', label: 'Lao', default: false },
    { code: 'la', label: 'Latin', default: false },
    { code: 'lv', label: 'Latvian', default: false },
    { code: 'li', label: 'Limburgan', default: false },
    { code: 'li', label: 'Limburger', default: false },
    { code: 'li', label: 'Limburgish', default: false },
    { code: 'ln', label: 'Lingala', default: false },
    { code: 'lt', label: 'Lithuanian', default: false },
    { code: 'lb', label: 'Luxembourgish', default: false },
    { code: 'lb', label: 'Letzeburgesch', default: false },
    { code: 'lu', label: 'Luba-Katanga', default: false },
    { code: 'lg', label: 'Ganda', default: false },
    { code: 'mk', label: 'Macedonian', default: false },
    { code: 'mh', label: 'Marshallese', default: false },
    { code: 'ml', label: 'Malayalam', default: false },
    { code: 'mi', label: 'Maori', default: false },
    { code: 'mr', label: 'Marathi', default: false },
    { code: 'ms', label: 'Malay', default: false },
    { code: 'mg', label: 'Malagasy', default: false },
    { code: 'mt', label: 'Maltese', default: false },
    { code: 'mo', label: 'Moldavian', default: false },
    { code: 'mn', label: 'Mongolian', default: false },
    { code: 'na', label: 'Nauru', default: false },
    { code: 'nv', label: 'Navajo', default: false },
    { code: 'nv', label: 'Navaho', default: false },
    { code: 'nr', label: 'Ndebele South', default: false },
    { code: 'nr', label: 'South Ndebele', default: false },
    { code: 'nr', label: 'Ndebele North', default: false },
    { code: 'nd', label: 'North Ndebele', default: false },
    { code: 'ng', label: 'Ndonga', default: false },
    { code: 'ne', label: 'Nepali', default: false },
    { code: 'nl', label: 'Dutch', default: false },
    { code: 'nn', label: 'Norwegian Nynorsk', default: false },
    { code: 'nn', label: 'Nynorsk Norwegian', default: false },
    { code: 'nb', label: 'Bokmål Norwegian', default: false },
    { code: 'nb', label: 'Norwegian Bokmål', default: false },
    { code: 'no', label: 'Norwegian', default: false },
    { code: 'ny', label: 'Chichewa', default: false },
    { code: 'ny', label: 'Nyanja', default: false },
    { code: 'oc', label: 'Occitan ', default: false },
    { code: 'oc', label: 'Provençal', default: false },
    { code: 'oj', label: 'Ojibwa', default: false },
    { code: 'or', label: 'Oriya', default: false },
    { code: 'om', label: 'Oromo', default: false },
    { code: 'os', label: 'Ossetian', default: false },
    { code: 'os', label: 'Ossetic', default: false },
    { code: 'pa', label: 'Panjabi', default: false },
    { code: 'pa', label: 'Punjabi', default: false },
    { code: 'pi', label: 'Pali', default: false },
    { code: 'pl', label: 'Polish', default: false },
    { code: 'pt', label: 'Portuguese', default: false },
    { code: 'ps', label: 'Pushto', default: false },
    { code: 'qu', label: 'Quechua', default: false },
    { code: 'rm', label: 'Romansh', default: false },
    { code: 'ro', label: 'Romanian', default: false },
    { code: 'rn', label: 'Rundi', default: false },
    { code: 'ru', label: 'Russian', default: false },
    { code: 'sg', label: 'Sango', default: false },
    { code: 'sa', label: 'Sanskrit', default: false },
    { code: 'sr', label: 'Serbian', default: false },
    { code: 'si', label: 'Sinhala', default: false },
    { code: 'si', label: 'Sinhalese', default: false },
    { code: 'sk', label: 'Slovak', default: false },
    { code: 'sl', label: 'Slovenian', default: false },
    { code: 'se', label: 'Northern Sami', default: false },
    { code: 'sm', label: 'Samoan', default: false },
    { code: 'sn', label: 'Shona', default: false },
    { code: 'sd', label: 'Sindhi', default: false },
    { code: 'so', label: 'Somali', default: false },
    { code: 'st', label: 'Sotho Southern', default: false },
    { code: 'es', label: 'Spanish', default: false },
    { code: 'es', label: 'Castilian', default: false },
    { code: 'sc', label: 'Sardinian', default: false },
    { code: 'ss', label: 'Swati', default: false },
    { code: 'su', label: 'Sundanese', default: false },
    { code: 'sw', label: 'Swahili', default: false },
    { code: 'sv', label: 'Swedish', default: false },
    { code: 'ty', label: 'Tahitian', default: false },
    { code: 'ta', label: 'Tamil', default: false },
    { code: 'tt', label: 'Tatar', default: false },
    { code: 'te', label: 'Telugu', default: false },
    { code: 'tg', label: 'Tajik', default: false },
    { code: 'tl', label: 'Tagalog', default: false },
    { code: 'th', label: 'Thai', default: false },
    { code: 'ti', label: 'Tigrinya', default: false },
    { code: 'to', label: 'Tonga ', default: false },
    { code: 'to', label: 'Tonga Islands', default: false },
    { code: 'tn', label: 'Tswana', default: false },
    { code: 'ts', label: 'Tsonga', default: false },
    { code: 'tk', label: 'Turkmen', default: false },
    { code: 'tr', label: 'Turkish', default: false },
    { code: 'tw', label: 'Twi', default: false },
    { code: 'ug', label: 'Uighur', default: false },
    { code: 'ug', label: 'Uyghur', default: false },
    { code: 'uk', label: 'Ukrainian', default: false },
    { code: 'ur', label: 'Urdu', default: false },
    { code: 'uz', label: 'Uzbek', default: false },
    { code: 've', label: 'Venda', default: false },
    { code: 'vi', label: 'Vietnamese', default: false },
    { code: 'vo', label: 'Volapük', default: false },
    { code: 'wa', label: 'Walloon', default: false },
    { code: 'wo', label: 'Wolof', default: false },
    { code: 'xh', label: 'Xhosa', default: false },
    { code: 'yi', label: 'Yiddish', default: false },
    { code: 'yo', label: 'Yoruba', default: false },
    { code: 'za', label: 'Zhuang Chuang', default: false },
    { code: 'zu', label: 'Zulu', default: false },
    { code: 'AsT', label: 'Asante Twi', default: false },
    { code: 'AkT', label: 'Akuapem Twi', default: false },
    { code: 'Ew', label: 'Ewe', default: false },
    { code: 'Ga', label: 'Ga', default: false },
    { code: 'Mfts', label: 'Mfantse' }
]
